---
templates:
  tv:
    thetvdb_lookup: true
    verify_ssl_certificates: false
    quality: "720p"
    series:
      hdGroup:
      - "American Horror Story"
      - "Arrow"
      - "Brooklyn Nine-Nine"
      - "Fargo"
      - "Game of Thrones"
      - "It's Always Sunny in Philadelphia"
      - "Last Week Tonight"
      - "NTSF:SD:SUV::"
      - "New Girl"
      - "Outlander"
      - "Rick and Morty"
      - "The Blacklist"
      - "The Expanse"
      - "The Flash"
      - "The Late Show with Stephen Colbert"
      - "The League"
      - "The Walking Dead"
      settings:
        hdGroup:
          target: "720p hdtv+"
          timeframe: "6 hours"
          propers: "12 hours"
        stdGroup:
          target: "hdtv+ <=720p"
          propers: "12 hours"
          timeframe: "6 hours"
    exists_series:
      allow_different_qualities: true
      path: "/media/Storage/Share/Videos/"
    transmission:
      host: "localhost"
      port: 9091
      username: "transmission"
      password: "transrpc"
      addpaused: false
      path: "/media/Storage/Share/Videos/{{series_name}}/Season {{series_season}}/"
      main_file_only: true
      ratio: 0.025
    clean_transmission:
      host: "localhost"
      port: 9091
      username: "transmission"
      password: "transrpc"
      finished_for: "10 minutes"
      min_ratio: 0.01
tasks:
  showrss:
    rss:
      url: "http://showrss.info/rss.php?user_id=88392&hd=null&proper=null"
    template: "tv"
    priority: 1
  kat-720p:
    priority: 2
    rss:
      url: "https://kat.cr/usearch/720p%20category%3Atv%20eztv%20OR%20ettv%20OR%20vtv/?rss=1"
    verify_ssl_certificates: false
    template: "tv"
  showrss-all:
    priority: 5
    rss:
      url: "http://showrss.info/user/16240.rss?magnets=true&namespaces=true&name=clean&quality=null&re=null"
    template: "tv"
email:
  from: "dwubutv@gmail.com"
  to: "dwhend0@gmail.com"
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  smtp_username: "dwubutv"
  smtp_password: "thz76j2!"
  smtp_tls: true