---
templates:
  global:
    regexp:
      reject:
      - "ipod"
      - "french"
      - "spanish"
      - "german"
      - "dutch"
      - "russian"
      - "(?i)[ .]webrip[ .]"
      - "(?i)[ .]cam[ .]"
      - "(?i)[ .]bdscr[ .]"
      - "(?i)[ .]dvdscr[ .]"
      - "(?i)[ .]preair[ .]"
      - "(?i)[ .]ppvrip[ .]"
      - "(?i)[ .]r5[ .]"
      - "(?i)[ .]tc[ .]"
      - "(?i)[ .]ts[ .]"
      - "(?i)[ .]ecc[ .]"
      - "(?i)[ .]avc[ .]"
      - "(?i)[ .]qebs[ .]"
      - "(?i)[ .]hdtc[ .]"
      - "(?i)[ .]hdcam[ .]"
    transmission:
      host: "firefly.home.lan"
      ratio: 0.01
      addpaused: false
      main_file_only: true
      skip_files:
      - "*.nfo"
      - "*.sfv"
      - "*.[sS]ample"
      - "*.txt"
      include_subs: false
    clean_transmission:
      host: "localhost"
      port: 9091
      finished_for: "10 minutes"
      min_ratio: 0.01
      enabled: true
    email:
      from: "firefly@home.lan"
      smtp_host: "firefly.home.lan"
      smtp_port: 587
      template: "html-downloaded.template"
      to:
      - "Jon.Reckner@gmail.com"
      - "kmburt2@uky.edu"
  tv:
    thetvdb_lookup: true
    verify_ssl_certificates: true
    series:
      hdGroup:
      - "12 Monkeys"
      - "Arrow"
      - "Blindspot"
      - "Bones"
      - "Colony"
      - "Criminal Minds"
      - "DCs Legends of Tomorrow"
      - "Dark Matter"
      - "Fear the Walking Dead"
      - "Game of Thrones"
      - "Gotham"
      - "Grimm"
      - "Homeland"
      - "Into the Badlands"
      - "LEGO Star Wars Droid Tales"
      - "Marvels Agent Carter"
      - "Marvels Agents of S.H.I.E.L.D."
      - "Marvels Daredevil"
      - "Minority Report"
      - "Mr Robot"
      - NCIS:
          exact: true
      - "NCIS Los Angeles"
      - Once Upon a Time:
          exact: true
      - "Person of Interest"
      - "Shadowhunters"
      - "Sherlock"
      - "Sleepy Hollow"
      - "Star Wars Rebels"
      - "Supergirl"
      - "Supernatural"
      - "The Blacklist"
      - "The Expanse"
      - "The Flash"
      - "The Last Ship"
      - "The Shannara Chronicles"
      - "The Walking Dead"
      - "True Detective"
      stdGroup:
      - "Archer"
      - Cold Justice:
          quality: "sdtv+"
      - "Family Guy"
      - "It's Always Sunny in Philadelphia"
      - "Modern Family"
      - "New Girl"
      - "The Big Bang Theory"
      - "The Vampire Diaries"
      - "Vikings"
      - "Workaholics"
      settings:
        hdGroup:
          timeframe: "20 hours"
          propers: "24 hours"
          target: "720p hdtv+"
        stdGroup:
          timeframe: "20 hours"
          propers: "20 hours"
          target: "<=720p"
    exists_series:
      allow_different_qualities: true
      path: "/media/raid5-1/public/Videos/TV Shows/"
    set:
      path: "/media/raid5-1/public/Videos/TV Shows/%(series_name)s/Season %(series_season)d"
tasks:
  tvShows:
    template: "tv"
    inputs:
    - rss: "http://showrss.info/user/28449.rss?magnets=true&namespaces=true&name=clean"
    - rss: "https://kat.cr/usearch/720p%20category%3Atv%20eztv%20OR%20ettv%20OR%20vtv/?rss=1"
    - rss: "https://kat.cr/usearch/category%3Atv%20eztv%20OR%20ettv%20OR%20vtv/?rss=1"
    - rss: "http://torrentz.eu/feed?q=tv+shows"
    - rss: "https://eztv.ag/ezrss.xml"
  search:
    template: "tv"
    discover:
      what:
      - emit_series:
          from_start: true
      from:
      - torrentz: "verified"
      - kat:
          category: "tv"
          verified: true
      interval: "1 day"